"""fix relationships and marks

Revision ID: e87c7cf9183b
Revises: 926235163b6f
Create Date: 2026-02-27 18:31:49.202859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87c7cf9183b'
down_revision: Union[str, Sequence[str], None] = '926235163b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('majors', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('majors', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
